import './globals.css'
import { Architects_Daughter, Poppins } from 'next/font/google'
import { NextAuthProvider } from './providers'
import Navbar from '@/components/Navbar'

import type { AppContext } from 'next/app';
import { getSession } from 'next-auth/react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
  variable: '--font-poppins'
})

const architects = Architects_Daughter({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-architects'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${poppins.variable} ${architects.variable} bg-black/10`} lang="en">
      <NextAuthProvider>
        <body className={''}>
          {/* @ts-expect-error Async Server Component */}
          <Navbar />
          {children}
        </body>
      </NextAuthProvider>
    </html>
  )
}

RootLayout.getInitialProps = async ({ Component, ctx }: AppContext) => {
  let pageProps = {};
  if (Component.getInitialProps) {
    pageProps = await Component.getInitialProps(ctx);
  }

  return {
    pageProps: {
      ...pageProps,
      session: await getSession(ctx)
    }
  };
};